[홈] 무한 캐러셀 구현
boostcampwm-2022/iOS01-Capsule pull request #123
Opened 2022-12-15 12:52 UTC by solbat

## 제출 전 필수 확인 사항:

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코드 컨벤션을 준수하는가?
- [x] 빌드가 되는 코드인가요?
- [x] 버그가 발생하지 않는지 충분히 테스트 해봤나요?

## 작업 내용:

- 무한 캐러셀 구현

2022-12-15 12:57 UTC, trumanfromkorea requested changes
고생하셨습니당

2022-12-15 12:57 UTC, trumanfromkorea commented on SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
> +    var datasource: [HomeCapsuleCellItem] = []
1. datasource 라는 변수명이 CollectionView 의 DataSource 와 헷갈릴 가능성이 있다고 생각합니다!
2. 해당 데이터는 ViewModel 이 가지고 있는게 자연스럽다고 생각합니다!

2022-12-15 12:57 UTC, trumanfromkorea commented on SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
> +                            .compactMap({ $0 }) // + Array(repeating: nil, count: Int.max)
큰 상관은 없지만 소괄호를 제외해도 될것 같아요

그리고 해당 라인을 없애고 58번째 라인의 map 메소드를 compactMap 으로 바꿔도 같은 기능을 하지 않을까 싶네요~

2022-12-15 12:57 UTC, trumanfromkorea commented on SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
> +                        Thread.sleep(forTimeInterval: 0.01)
여기서 메인스레드를 재우는 이유가 있나요?!

2022-12-15 13:41 UTC, solbat commented on SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
> +    var datasource: [HomeCapsuleCellItem] = []
1. 변경하였습니다!
2. VM으로 옮겼습니다!

2022-12-15 13:42 UTC, solbat commented on SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewModel.swift
> +                            .compactMap({ $0 }) // + Array(repeating: nil, count: Int.max)
compactMap으로 변경하였습니다!

2022-12-15 14:08 UTC, solbat commented on SpaceCapsule/SpaceCapsule/Scene/TabBar/Home/HomeViewController.swift
> +                        Thread.sleep(forTimeInterval: 0.01)
앱을 처음 실행 시 간혹 캡슐이 짤려서 두줄로 나오는 버그가 발생하였습니다.
저는 이 문제가 컬렉션뷰가 불린 후 초기 화면 설정을 위해 scrollToItem을 실행 시에 발생하는 버그라고 판단하였습니다.
따라서 먼저 컬렉션뷰가 초기에 멀쩡하게 호출된 후에 텀을 두어 scrollToItem 함수가 실행되도록 하고자 하였습니다........
그러나 간헐적으로 버그가 발생하기는 합니다..

2023-01-09 13:03 UTC, chansooo approved these changes
LGTM👍

2026-07-15 21:16 UTC, closed without merging